file = open("demo.txt","w")
file.write("This is file management demo using Python")
file.close()
print("File Written Successfully")
print("-" * 40)

file = open("demo.txt","r")
print(file.read())
file.close()
print("-" * 40)

file = open("demo.txt","a")
file.write("\nFile is appended by A operation")
file.close()
print("File Appended Successfully")
print("-" * 40)

file = open("demo.txt","r")
print(file.read())
file.close()
print("-" * 40)

file = open("tops2.txt","w+")
file.write("This is python w+ operation demo")
print("File current position :", file.tell())
file.seek(0)
print("file data :", file.read())
file.close()
print("-" * 40)

file = open("tops2.txt","r+")
print("file data :", file.read())
file.write("\nThis is python r+ operation demo")
print("File current position :", file.tell())
file.seek(0)
file.close()
print("-" * 40)
