# Generated by Django 6.0.4 on 2026-05-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
